import type { EngineScenario } from '../types';

const CENTER_TEXT = `<|size=30 bold color=purple|>🍨 Sundae<|/color|> has fancy text!<|/size /bold|>

You can use <|bold|>bold<|/bold|> and <|italic|>italic<|/italic|> text, and <|color=red|>color<|/color|>.
And you can use them <|bold italic color=blue|>together!<|/bold /italic /color|>

<|size=42|>Or<|/size|> <|size=37|>mix<|/size|> <|size=32|>and<|/size|> <|size=28|>match<|/size|> <|size=23|>different<|/size|> <|size=19|>sizes<|/size|> <|size=15|>in<|/size|> <|size=13|>the<|/size|> <|size=11|>same<|/size|> <|size=9|>text!<|/size|>
`;

const AXIS_COLOR = '#444444';
const ALIGN_TEXT_COLOR = '#BBBBBB';
const ALIGN_TEXT_SIZE = 10;
const ALIGN_TEXT_PADDING = 6;
const BOX_SIZE = { x: 620, y: 400 };

const ALIGN_BG_COLORS = {
    'top-left': '#e76f51',
    'top-center': '#e9c46a',
    'top-right': '#ee6c4d',
    left: '#2a9d8f',
    right: '#2a9d8f',
    'bottom-left': '#e76f51',
    'bottom-center': '#e9c46a',
    'bottom-right': '#e76f51',
} as const;

export const textRendering: EngineScenario = async (harness) => {
    harness.engine.openScene({
        name: 'Text Rendering',
        entities: [
            {
                type: 'line',
                name: 'x-axis',
                start: { x: -500, y: 0 },
                end: { x: 500, y: 0 },
                lineColor: AXIS_COLOR,
                zIndex: -1,
            },
            {
                type: 'line',
                name: 'y-axis',
                start: { x: 0, y: -500 },
                end: { x: 0, y: 500 },
                lineColor: AXIS_COLOR,
                zIndex: -1,
            },
            {
                type: 'text',
                text: 'X-Axis',
                textAlign: 'center',
                positionRelativeToCamera: { x: 'none', y: 'center' },
                color: AXIS_COLOR,
            },
            {
                type: 'text',
                text: 'Y-Axis',
                textAlign: 'center',
                positionRelativeToCamera: { x: 'center', y: 'none' },
                color: AXIS_COLOR,
            },
            {
                type: 'rectangle',
                lineColor: AXIS_COLOR,
                lineWidth: 2,
                scale: BOX_SIZE,
                zIndex: -1,
            },
            {
                type: 'text',
                text: CENTER_TEXT,
                textAlign: 'center',
                trim: 'none',
                fontSize: 20,
                background: true,
                padding: 12,
                scale: 0.75,
                scaleRelativeToCamera: true,
                zIndex: 1,
            },
            {
                name: 'top-left',
                type: 'text',
                text: 'Top Left',
                textAlign: 'bottom-right',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                position: { x: -BOX_SIZE.x / 2, y: -BOX_SIZE.y / 2 },
                background: ALIGN_BG_COLORS['top-left'],
                padding: ALIGN_TEXT_PADDING,
                zIndex: 2,
            },
            {
                name: 'bottom-right',
                type: 'text',
                text: 'Bottom Right',
                textAlign: 'top-left',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                position: { x: BOX_SIZE.x / 2, y: BOX_SIZE.y / 2 },
                background: ALIGN_BG_COLORS['bottom-right'],
                padding: ALIGN_TEXT_PADDING,
                zIndex: 2,
            },
            {
                name: 'top-center',
                type: 'text',
                text: 'Top Center',
                textAlign: 'bottom-center',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                position: { x: 0, y: -BOX_SIZE.y / 2 },
                background: ALIGN_BG_COLORS['top-center'],
                padding: ALIGN_TEXT_PADDING,
                zIndex: 2,
            },
            {
                name: 'bottom-center',
                type: 'text',
                text: 'Bottom Center',
                textAlign: 'top-center',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                position: { x: 0, y: BOX_SIZE.y / 2 },
                background: ALIGN_BG_COLORS['bottom-center'],
                padding: ALIGN_TEXT_PADDING,
                zIndex: 2,
            },
            {
                name: 'left',
                type: 'text',
                text: 'Left',
                textAlign: 'right',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                position: { x: -BOX_SIZE.x / 2, y: 0 },
                background: ALIGN_BG_COLORS.left,
                padding: ALIGN_TEXT_PADDING,
                zIndex: 2,
            },
            {
                name: 'right',
                type: 'text',
                text: 'Right',
                textAlign: 'left',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                position: { x: BOX_SIZE.x / 2, y: 0 },
                background: ALIGN_BG_COLORS.right,
                padding: ALIGN_TEXT_PADDING,
                zIndex: 2,
            },
            {
                name: 'bottom-left',
                type: 'text',
                text: 'Bottom Left',
                textAlign: 'top-right',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                position: { x: -BOX_SIZE.x / 2, y: BOX_SIZE.y / 2 },
                background: ALIGN_BG_COLORS['bottom-left'],
                padding: ALIGN_TEXT_PADDING,
                zIndex: 2,
            },
            {
                name: 'top-right',
                type: 'text',
                text: 'Top Right',
                textAlign: 'bottom-left',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                position: { x: BOX_SIZE.x / 2, y: -BOX_SIZE.y / 2 },
                background: ALIGN_BG_COLORS['top-right'],
                padding: ALIGN_TEXT_PADDING,
                zIndex: 2,
            },
            {
                name: 'top-left-screen',
                type: 'text',
                text: 'Top Left\nScreen',
                textAlign: 'bottom-right',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                background: ALIGN_BG_COLORS['top-left'],
                positionRelativeToCamera: 'start',
                padding: { x1: 12, y1: 12, x2: 6, y2: 6 },
                zIndex: 2,
            },
            {
                name: 'top-center-screen',
                type: 'text',
                text: 'Top Center\nScreen',
                textAlign: 'bottom-center',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                background: ALIGN_BG_COLORS['top-center'],
                positionRelativeToCamera: { x: 'center', y: 'start' },
                padding: { x1: 6, y1: 12, x2: 6, y2: 6 },
                zIndex: 2,
            },
            {
                name: 'top-right-screen',
                type: 'text',
                text: 'Top Right\nScreen',
                textAlign: 'bottom-left',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                background: ALIGN_BG_COLORS['top-right'],
                positionRelativeToCamera: { x: 'end', y: 'start' },
                padding: { x1: 6, y1: 12, x2: 12, y2: 6 },
                zIndex: 2,
            },
            {
                name: 'left-screen',
                type: 'text',
                text: 'Left\nScreen',
                textAlign: 'right',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                background: ALIGN_BG_COLORS.left,
                positionRelativeToCamera: { x: 'start', y: 'center' },
                padding: { x1: 12, y1: 6, x2: 6, y2: 6 },
                zIndex: 2,
            },
            {
                name: 'right-screen',
                type: 'text',
                text: 'Right\nScreen',
                textAlign: 'left',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                background: ALIGN_BG_COLORS.right,
                positionRelativeToCamera: { x: 'end', y: 'center' },
                padding: { x1: 6, y1: 6, x2: 12, y2: 6 },
                zIndex: 2,
            },
            {
                name: 'bottom-left-screen',
                type: 'text',
                text: 'Bottom Left\nScreen',
                textAlign: 'top-right',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                background: ALIGN_BG_COLORS['bottom-left'],
                positionRelativeToCamera: { x: 'start', y: 'end' },
                padding: { x1: 12, y1: 6, x2: 6, y2: 12 },
                zIndex: 2,
            },
            {
                name: 'bottom-center-screen',
                type: 'text',
                text: 'Bottom Center\nScreen',
                textAlign: 'top-center',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                background: ALIGN_BG_COLORS['bottom-center'],
                positionRelativeToCamera: { x: 'center', y: 'end' },
                padding: { x1: 6, y1: 6, x2: 6, y2: 12 },
                zIndex: 2,
            },
            {
                name: 'bottom-right-screen',
                type: 'text',
                text: 'Bottom Right\nScreen',
                textAlign: 'top-left',
                trim: 'none',
                fontSize: ALIGN_TEXT_SIZE,
                color: ALIGN_TEXT_COLOR,
                bold: true,
                background: ALIGN_BG_COLORS['bottom-right'],
                positionRelativeToCamera: 'end',
                padding: { x1: 6, y1: 6, x2: 12, y2: 12 },
                zIndex: 2,
            },
        ],
    });
};
